export const CATEGORIES = [
  {
    id: 'management', label: 'Management', shortDesc: 'Développez vos compétences managériales',
    desc: 'Développez vos compétences managériales, inspirez vos équipes et pilotez la performance avec leadership.',
    subcats: ['Pratiques managériales', 'Conduite de projet', 'Leadership & motivation', 'Management des équipes', 'Gestion du changement']
  },
  {
    id: 'bureautique', label: 'Bureautique', shortDesc: 'Maîtrisez les outils du quotidien',
    desc: 'Boostez votre productivité grâce à nos formations bureautiques adaptées à tous niveaux.',
    subcats: ['Excel', 'Word', 'PowerPoint', 'Outlook', 'Google Suite', 'OneNote']
  },
  {
    id: 'rh', label: 'Ressources Humaines', shortDesc: 'Recrutez, développez, fidélisez',
    desc: 'Recrutez, développez et fidélisez vos talents pour accompagner la performance de votre organisation.',
    subcats: ['Recrutement & intégration', 'Droit du travail', 'Paie & administration', 'Formation & GPEC', 'QVT & bien-être']
  },
  {
    id: 'ia', label: 'Intelligence Artificielle', shortDesc: "L'IA au service de votre métier",
    desc: "Intégrez l'IA dans vos pratiques professionnelles pour gagner en efficacité et prendre de l'avance.",
    subcats: ['ChatGPT & Assistants IA', 'IA générative', 'Automatisation', 'Copilot Microsoft 365', 'Data & Analytics']
  },
  {
    id: 'marketing', label: 'Marketing & Communication', shortDesc: 'Développez votre visibilité',
    desc: 'Développez vos ventes, fidélisez vos clients et boostez votre visibilité grâce aux meilleures pratiques.',
    subcats: ['Marketing digital', 'Réseaux sociaux', 'SEO / SEA', "Communication d'entreprise", 'Techniques de vente']
  },
  {
    id: 'droit', label: 'Droit & Réglementation', shortDesc: 'Maîtrisez le cadre légal',
    desc: 'Maîtrisez le cadre légal et réglementaire pour sécuriser vos pratiques professionnelles.',
    subcats: ['RGPD & données personnelles', 'Droit du travail', 'Droit commercial', 'Droit social', 'Contrats & obligations']
  },
  {
    id: 'entrepreneuriat', label: 'Entrepreneuriat', shortDesc: "De l'idée au projet d'entreprise",
    desc: "Entreprendre, innover, réussir : donnez vie à vos projets d'entreprise avec les bons outils.",
    subcats: ["Création d'entreprise", 'Business plan & stratégie', 'Financement', 'Développement commercial', "Gestion d'entreprise"]
  }
];

export const FORMATIONS = [
  { id:'f1', title:'Manager de proximité', category:'management', subcategory:'Management des équipes', duration:2, hours:14, price:916, modes:['presentiel','distanciel'], cpf:true, popular:true,
    description:"Acquérir les fondamentaux du management opérationnel pour encadrer efficacement une équipe au quotidien.",
    objectives:["Comprendre son rôle et ses responsabilités de manager","Développer son style de management adapté","Motiver et engager ses collaborateurs","Gérer les situations difficiles avec sérénité"],
    program:["Jour 1 — Le rôle du manager : posture, délégation, communication","Jour 2 — Outils pratiques : entretiens, feedback, gestion des conflits"]},
  { id:'f2', title:'Conduite de réunion efficace', category:'management', subcategory:'Pratiques managériales', duration:1, hours:7, price:580, modes:['presentiel','distanciel'], cpf:false,
    description:"Maîtriser les techniques d'animation pour conduire des réunions productives et engageantes.",
    objectives:["Préparer et structurer une réunion","Animer avec méthode et dynamisme","Gérer les participants difficiles","Produire des livrables actionnables"],
    program:["Matin — Préparation et cadrage : types de réunions, ordre du jour, objectifs","Après-midi — Animation et suivi : techniques, compte-rendu, plan d'action"]},
  { id:'f3', title:"Leadership et motivation d'équipe", category:'management', subcategory:'Leadership & motivation', duration:2, hours:14, price:980, modes:['presentiel','distanciel'], cpf:true, popular:true,
    description:"Développer son leadership naturel et créer les conditions de la performance collective.",
    objectives:["Identifier son style de leadership","Créer une vision mobilisatrice","Développer l'engagement et la motivation","Accompagner les talents individuellement"],
    program:["Jour 1 — Leadership : styles, posture, influence, vision","Jour 2 — Motivation : leviers, reconnaissance, accompagnement individuel"]},
  { id:'f4', title:'Gestion des conflits au travail', category:'management', subcategory:'Pratiques managériales', duration:2, hours:14, price:916, modes:['presentiel','distanciel'], cpf:false,
    description:"Identifier, prévenir et résoudre les conflits pour maintenir un climat de travail serein.",
    objectives:["Comprendre les sources de conflits","Développer une posture assertive","Désamorcer les tensions","Trouver des solutions durables"],
    program:["Jour 1 — Comprendre les conflits : typologies, origines, signaux faibles","Jour 2 — Résoudre les conflits : médiation, communication non violente"]},
  { id:'f5', title:'Excel — Initiation', category:'bureautique', subcategory:'Excel', duration:2, hours:14, price:700, modes:['presentiel','distanciel'], cpf:true, popular:true,
    description:"Prendre en main Excel pour créer et gérer des tableaux de données simples et efficaces.",
    objectives:["Naviguer dans l'interface Excel","Saisir et mettre en forme des données","Utiliser les formules de base","Créer des graphiques simples"],
    program:["Jour 1 — Interface, saisie, mise en forme, formules essentielles","Jour 2 — Fonctions, graphiques, impression, gestion des classeurs"]},
  { id:'f6', title:'Excel — Perfectionnement', category:'bureautique', subcategory:'Excel', duration:2, hours:14, price:700, modes:['presentiel','distanciel'], cpf:true,
    description:"Aller plus loin avec Excel : fonctions avancées, tableaux croisés dynamiques et automatisation.",
    objectives:["Maîtriser les fonctions avancées (RECHERCHEV, SI imbriqués)","Exploiter les tableaux croisés dynamiques","Automatiser avec des macros simples","Visualiser avec des graphiques avancés"],
    program:["Jour 1 — Fonctions avancées, mise en forme conditionnelle, validation","Jour 2 — TCD, graphiques avancés, macros simples, Power Query introduction"]},
  { id:'f7', title:'PowerPoint — Présentations impactantes', category:'bureautique', subcategory:'PowerPoint', duration:1, hours:7, price:580, modes:['presentiel','distanciel'], cpf:false,
    description:"Créer des présentations visuellement percutantes qui captivent l'audience.",
    objectives:["Structurer un message fort","Maîtriser les outils de mise en page","Intégrer animations et transitions","Préparer une présentation professionnelle"],
    program:["Matin — Structure, masques, charte graphique, iconographie","Après-midi — Animations, transitions, export, conseils de prise de parole"]},
  { id:'f8', title:'Google Suite & outils collaboratifs', category:'bureautique', subcategory:'Google Suite', duration:1, hours:7, price:620, modes:['distanciel'], cpf:false,
    description:"Maîtriser la suite Google Workspace pour collaborer efficacement en équipe.",
    objectives:["Utiliser Gmail, Drive, Docs, Sheets, Slides","Partager et co-éditer des documents","Gérer son agenda Google","Organiser ses fichiers en équipe"],
    program:["Journée complète — Gmail & Agenda, Drive & partage, Docs, Sheets, Slides, Meet"]},
  { id:'f9', title:"L'entretien professionnel", category:'rh', subcategory:'Formation & GPEC', duration:1, hours:7, price:580, modes:['presentiel','distanciel'], cpf:false, popular:true,
    description:"Maîtriser les obligations légales et les bonnes pratiques de l'entretien professionnel.",
    objectives:["Connaître le cadre légal de l'entretien professionnel","Préparer et conduire l'entretien","Identifier les besoins de formation","Rédiger les comptes-rendus réglementaires"],
    program:["Matin — Cadre légal, obligations, articulation avec l'entretien annuel","Après-midi — Conduite de l'entretien, outils, mises en situation"]},
  { id:'f10', title:'Recrutement et intégration', category:'rh', subcategory:'Recrutement & intégration', duration:2, hours:14, price:916, modes:['presentiel','distanciel'], cpf:true,
    description:"Maîtriser tout le processus de recrutement : de la définition du besoin à l'intégration réussie.",
    objectives:["Définir le profil et rédiger l'offre","Conduire des entretiens efficaces","Évaluer les candidats objectivement","Réussir l'onboarding"],
    program:["Jour 1 — Besoin, sourcing, offres d'emploi, tri des candidatures","Jour 2 — Entretiens, évaluation, décision, intégration"]},
  { id:'f11', title:'Initiation à la paie', category:'rh', subcategory:'Paie & administration', duration:3, hours:21, price:1100, modes:['presentiel','distanciel'], cpf:true,
    description:"Acquérir les bases de la gestion de la paie : calcul des éléments de rémunération et production du bulletin.",
    objectives:["Comprendre la structure du bulletin de paie","Calculer les cotisations sociales","Gérer les absences et congés","Connaître les obligations légales"],
    program:["Jour 1 — Structure de la paie, contrat de travail, éléments de base","Jour 2 — Cotisations, allègements, charges patronales","Jour 3 — Absences, congés, rupture du contrat, DSN"]},
  { id:'f12', title:'Droit du travail — Fondamentaux', category:'rh', subcategory:'Droit du travail', duration:2, hours:14, price:916, modes:['presentiel','distanciel'], cpf:false,
    description:"Maîtriser les règles essentielles du droit du travail pour sécuriser ses pratiques RH et managériales.",
    objectives:["Connaître les sources du droit du travail","Maîtriser le contrat de travail","Gérer la durée du travail et les congés","Comprendre les procédures disciplinaires"],
    program:["Jour 1 — Sources du droit, contrats, période d'essai, clauses spécifiques","Jour 2 — Temps de travail, congés, sanctions disciplinaires, rupture du contrat"]},
  { id:'f13', title:'ChatGPT pour les professionnels', category:'ia', subcategory:'ChatGPT & Assistants IA', duration:1, hours:7, price:650, modes:['presentiel','distanciel'], cpf:false, popular:true,
    description:"Utiliser ChatGPT et les assistants IA dans son quotidien professionnel pour gagner en productivité.",
    objectives:["Comprendre le fonctionnement des LLM","Rédiger des prompts efficaces","Utiliser l'IA pour la rédaction et la synthèse","Identifier les limites et les risques"],
    program:["Matin — Fonctionnement, cas d'usage, technique de prompting","Après-midi — Cas pratiques par métier, outils complémentaires, enjeux éthiques"]},
  { id:'f14', title:'IA générative en entreprise', category:'ia', subcategory:'IA générative', duration:2, hours:14, price:1100, modes:['presentiel','distanciel'], cpf:true,
    description:"Déployer une stratégie IA dans son organisation et accompagner la transformation des métiers.",
    objectives:["Cartographier les cas d'usage IA de son secteur","Évaluer les outils du marché","Définir une feuille de route IA","Gérer les risques et la conformité"],
    program:["Jour 1 — Panorama de l'IA générative, usages, outils (texte, image, code)","Jour 2 — Stratégie d'intégration, gouvernance, change management"]},
  { id:'f15', title:"Automatiser ses tâches avec l'IA", category:'ia', subcategory:'Automatisation', duration:1, hours:7, price:750, modes:['distanciel'], cpf:false,
    description:"Créer des workflows automatisés avec les outils no-code et l'IA pour éliminer les tâches répétitives.",
    objectives:["Identifier les tâches automatisables","Utiliser Make / Zapier avec l'IA","Créer des assistants personnalisés","Mesurer les gains de productivité"],
    program:["Journée complète — Audit des tâches, Make/Zapier, GPT Actions, assistants personnalisés, cas pratiques"]},
  { id:'f16', title:'Copilot Microsoft 365', category:'ia', subcategory:'Copilot Microsoft 365', duration:1, hours:7, price:680, modes:['presentiel','distanciel'], cpf:false,
    description:"Exploiter Copilot intégré dans Word, Excel, PowerPoint, Teams et Outlook pour travailler plus vite.",
    objectives:["Activer et configurer Copilot","Utiliser Copilot dans chaque application Office","Rédiger, synthétiser, analyser avec l'IA","Optimiser ses prompts dans le contexte Office"],
    program:["Matin — Introduction, Copilot dans Word et Outlook","Après-midi — Copilot dans Excel, PowerPoint, Teams — cas pratiques"]},
  { id:'f17', title:'Marketing digital — Initiation', category:'marketing', subcategory:'Marketing digital', duration:2, hours:14, price:916, modes:['presentiel','distanciel'], cpf:true,
    description:"Comprendre les fondamentaux du marketing digital pour développer sa présence en ligne.",
    objectives:["Maîtriser les canaux digitaux","Construire une stratégie de contenu","Analyser ses performances","Lancer ses premières campagnes"],
    program:["Jour 1 — Écosystème digital, site web, SEO, e-mail marketing","Jour 2 — Réseaux sociaux, publicité en ligne, analytics, plan d'action"]},
  { id:'f18', title:'Réseaux sociaux professionnels', category:'marketing', subcategory:'Réseaux sociaux', duration:1, hours:7, price:580, modes:['presentiel','distanciel'], cpf:false,
    description:"Développer sa présence sur LinkedIn et les réseaux sociaux professionnels pour booster sa visibilité.",
    objectives:["Optimiser son profil LinkedIn","Créer du contenu engageant","Développer son réseau professionnel","Utiliser les outils de publication et d'analyse"],
    program:["Matin — Stratégie de personal branding, optimisation du profil","Après-midi — Création de contenu, calendrier éditorial, analytics"]},
  { id:'f19', title:'Référencement SEO — Fondamentaux', category:'marketing', subcategory:'SEO / SEA', duration:2, hours:14, price:950, modes:['presentiel','distanciel'], cpf:false,
    description:"Comprendre et appliquer les techniques de référencement naturel pour améliorer la visibilité de son site.",
    objectives:["Maîtriser les fondamentaux du SEO","Optimiser le contenu et la structure","Construire sa stratégie de liens","Utiliser Google Search Console"],
    program:["Jour 1 — Fonctionnement des moteurs, mots-clés, SEO technique","Jour 2 — Contenu, netlinking, mesures, outils (GSC, Semrush introduction)"]},
  { id:'f20', title:'RGPD — Se mettre en conformité', category:'droit', subcategory:'RGPD & données personnelles', duration:1, hours:7, price:650, modes:['presentiel','distanciel'], cpf:false, popular:true,
    description:"Comprendre le RGPD et mettre en place les actions nécessaires à la conformité de son organisation.",
    objectives:["Connaître les principes du RGPD","Identifier les données personnelles de son organisation","Mettre en place le registre des traitements","Gérer les droits des personnes"],
    program:["Matin — Cadre légal, définitions, grands principes du RGPD","Après-midi — Registre, DPO, violations de données, plan de mise en conformité"]},
  { id:'f21', title:'Droit commercial et des affaires', category:'droit', subcategory:'Droit commercial', duration:2, hours:14, price:916, modes:['presentiel','distanciel'], cpf:false,
    description:"Maîtriser les règles essentielles du droit commercial pour sécuriser ses relations d'affaires.",
    objectives:["Connaître les sources du droit commercial","Maîtriser les contrats commerciaux courants","Gérer les impayés et le recouvrement","Prévenir les litiges"],
    program:["Jour 1 — Actes de commerce, fonds de commerce, contrats types","Jour 2 — Responsabilité, garanties, contentieux commercial, médiation"]},
  { id:'f22', title:"Créer son entreprise — de l'idée au projet", category:'entrepreneuriat', subcategory:"Création d'entreprise", duration:2, hours:14, price:916, modes:['presentiel','distanciel'], cpf:true, popular:true,
    description:"Structurer son projet entrepreneurial et acquérir les bases indispensables pour créer son entreprise.",
    objectives:["Valider son idée et son marché","Choisir la bonne forme juridique","Construire son modèle économique","Connaître les démarches de création"],
    program:["Jour 1 — Idée, marché, positionnement, concurrence, modèle économique","Jour 2 — Statuts juridiques, financement, démarches administratives, réseaux d'appui"]},
  { id:'f23', title:'Construire son business plan', category:'entrepreneuriat', subcategory:'Business plan & stratégie', duration:1, hours:7, price:680, modes:['presentiel','distanciel'], cpf:false,
    description:"Apprendre à construire un business plan complet et convaincant pour séduire banques et investisseurs.",
    objectives:["Structurer son business plan","Réaliser ses prévisions financières","Présenter son projet de manière convaincante","Adapter son discours aux interlocuteurs"],
    program:["Matin — Structure du BP, étude de marché, modèle économique, résumé exécutif","Après-midi — Projections financières, plan de financement, pitch"]},
  { id:'f24', title:'Financement et aides à la création', category:'entrepreneuriat', subcategory:'Financement', duration:1, hours:7, price:650, modes:['distanciel'], cpf:false,
    description:"Identifier et mobiliser les aides, subventions et financements disponibles pour créer ou développer son entreprise.",
    objectives:["Connaître les dispositifs d'aide à la création","Identifier les aides régionales et nationales","Préparer un dossier de financement","Approcher les banques et investisseurs"],
    program:["Journée complète — ACRE, ARCE, PCE, aides régionales, BPI, love money, crowdfunding, banques"]}
];
